part of 'app_pages.dart';

abstract class Routes {
  static const SPLASH = '/splash';
  static const NAV = '/nav';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const FORGETPSW = '/forgetPsw';
  static const WALLET = '/wallet';
  static const WALLETLIST = '/wallet_list';
  static const BOARDLIST = '/board_list';
  static const BOARDDETAIL = '/board_detail';
  static const NFTDETAIL = '/nft_detail';
  static const SAFE = '/mine_safe';
  static const RESETPSW = '/reset_psw';
  static const AGREEMENT = '/agreement';
  static const PRIVACY = '/privacy';
  static const BANKCARD = '/bank_card';
  static const BINDINGBANKCARD = '/binding_bank_card';
  static const REALNAME = '/real_name';
  static const SERIES = '/series';
  static const SHARERANK = '/share_rank';
  static const MARKETRANK = '/market_rank';
  static const SYNTHESISLIST = '/synthesis_list';
  static const SYNTHESISDETAIL = '/synthesis_detail';
  static const BLINDBOXDETAIL = '/blind_box_detail';
  static const MINEBLINDBOXLIST = '/mine_blind_box_list';
  static const MINEBLINDBOXDETAIL = '/mine_blind_box_detail';
  static const MINEBLINDBOXOPEN = '/mine_blind_box_open';
  static const MARKETDETAIL = '/market_detail';
  static const PAY = '/pay';
  static const MINENFTDETAIL = '/mine_nft_detail';
  static const MINEALBUMLIST = '/mine_album_list';
  static const MINENFTLIST = '/mine_nft_list';
  static const MINEGIVELIST = '/mine_give_list';
  static const MINEPLATFORMORDERLIST = '/mine_platform_order_list';
  static const MINEPLATFORMORDERDETAIL = '/mine_platform_order_detail';
  static const MINEMARKETORDERLIST = '/mine_market_order_list';
  static const MINEMARKETORDERDETAIL = '/mine_market_order_detail';
  static const RESELL = '/resell';
  static const GIVE = '/give';
  static const THREE = '/three';
}